version: '3.8'

services:
  frontend:
    build:
      context: ./VibeTune.Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./VibeTune.Api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

